name: Deploy to Amazon ECS

on:
  workflow_run:
    workflows: [ "Terraform" ]
    types: [completed]
    branches: [ "main" ]

concurrency:
  group: ecr-backend
  cancel-in-progress: false
 

permissions:
  contents: read
  id-token: write


env:
  AWS_REGION: us-east-1                   
  ECR_REPOSITORY: ecr           
  ECS_SERVICE: backend                 
  ECS_CLUSTER: cloudtask-cluster               
  ECS_TASK_DEFINITION: task-definition.json
                                              
  CONTAINER_NAME: backend   

jobs:
  deploy:
    name: Build and Deploy ECS
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume:  arn:aws:iam::090243701151:role/ecr-githubrole
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
      run: |
          IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

          docker build -t "$IMAGE" -f ./backend/Dockerfile .

          docker push "$IMAGE"

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

    - name: Download Current ECS Task Definition
      run: |
        TASK_DEF_ARN=$(aws ecs describe-services \
        --services "$ECS_SERVICE" \
        --cluster "$ECS_CLUSTER" \
        --query 'service[0].taskDefinition' \
        --output text
        )

        if [ -z "$TASK_DEF_ARN" ] || [ "$TASK_DEF_ARN" = "None" ]; then
          echo "ECS service definition not found"
          exit 1
        fi

        aws ecs describe-task-definition \
            --task-definition "$TASK_DEF_ARN" \
            --query taskDefinition \
            --output json > "$ECS_TASK_DEFINITION"

    - name: Render Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
          