name: Terraform

on:
  push:
    branches: [ "main" ]

concurrency:
  group: terraform-dev
  cancel-in-progress: false


permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  arn:aws:iam::090243701151:role/terraform-githubrole
        aws-region: us-east-1

    - name: Get Caller identity
      run: aws sts get-caller-identity

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.15.7


    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init --reconfigure

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -recursive
    
    - name: Create Terrafrom Variables
      run: |
        cat > terraform.tfvars <<EOF
        region            = "us-east-1"
        cidr_block        = "10.0.0.0/16"
        availability_zone = ["us-east-1a", "us-east-1b"]
        account_id        = "090243701151"
        function_name     = "lambda-function"
        db_name           = "mydatabase"
        engine_version    = 17
        bucket            = "my-bucket-storage-9250"
        domain_name       = "orema-devops.xyz"
        aliases           = ["orema-devops.xyz"]
        image_tag         = "v1"
        api_domain_name   = "api.orema-devops.xyz" 
        EOF
     
    - name: Terraform Workspace
      run: |
        terraform workspace select dev || terraform workspace new dev

    - name: Terraform Validate
      run: terraform validate
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false -lock=false

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false -lock=false
 
   